# Generated by Django 5.2.12 on 2026-03-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0004_prediction_input_snapshot_alter_prediction_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mlmodel',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='total_predictions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mlmodel',
            name='traffic_percentage',
            field=models.FloatField(default=1.0),
        ),
    ]
