# Generated by Django 5.2.12 on 2026-04-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0007_prediction_explanation_tags_prediction_model_used'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('market_type', models.CharField(max_length=10)),
                ('risk_score', models.FloatField()),
                ('anomaly_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['symbol', 'created_at'], name='crypto_app__symbol_1c8304_idx')],
            },
        ),
    ]
