# Generated by Django 5.2.12 on 2026-04-03 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0008_livesignal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='social_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
