# Generated by Django 5.2.12 on 2026-04-15 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0012_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
