# Generated by Django 5.2.12 on 2026-04-17 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_app', '0013_remove_user_is_verified'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
